#!/bin/bash

for i in $@; do
    JOB=$HOME/mass-storage/JobArchive/2014-06-04-FMOground10ns
    PROJECT=$HOME/Code/photosynth/cGromCorrFMO
    
    fmo_traj_path=$JOB/gro/mdtraj$i.gro
    fmo_top_path=$JOB/FMO_conf/4BCL_pp.top
    bcx_itp_path=$JOB/FMO_conf/amber_mod.ff/bcx.itp
    #output_path=$PROJECT/data/CsvOut/2014B_MDPost/md$i
    output_path=$JOB/gro/dEcsv/dEcsv$i
    #output_path=md
    #output_path=$JOB/md

    num_frames=50000

    #scanlines=40000
    #num_frames=$(head $fmo_traj_path | grep 'Generated by trjconv')
    #dt=$(head $fmo_traj_path -n $scanframes | grep 'Generated by trjconv' | head -n 2 | tail -n 1)
    #num_2=$(tail $fmo_traj_path -n $scanframes | grep 'Generated by trjconv' | tail -n 1)
    #echo $dt
    #echo $num_2
    
    echo "Using file $fmo_traj_path, and computing dEcsv with $num_frames frames"
    
    $PROJECT/src/traj2dEcsv $fmo_traj_path $fmo_top_path $bcx_itp_path $output_path $num_frames
done
